
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-7pm-4
owner: ucsb-cs156-w24
repo_name: team02-w24-7pm-4
pull_requests: [{"author":{"id":"U_kgDOBXzOLw","is_bot":false,"login":"wesley-hung","name":""},"headRefName":"whung-Articles-42","number":53,"title":"Created DELETE api call for ArticlesController and corresponding tests ","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-4/pull/53"},{"author":{"id":"U_kgDOBXzOLw","is_bot":false,"login":"wesley-hung","name":""},"headRefName":"whung-Articles-41","number":52,"title":"Added PUT api call for ArticlesController and corresponding tests","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-4/pull/52"},{"author":{"id":"MDQ6VXNlcjQwNTQ2NDI3","is_bot":false,"login":"viditagrawal","name":""},"headRefName":"viditagrawal-createdbtable","number":51,"title":"created db and schema for ucsb organizations","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-4/pull/51"},{"author":{"id":"U_kgDOBXux7g","is_bot":false,"login":"wesleytruong","name":""},"headRefName":"wt-MenuItemReview-Controller-getbyid","number":50,"title":"Wt menu item review controller getbyid","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-4/pull/50"}]
