
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-7pm-4
owner: ucsb-cs156-w24
repo_name: team02-w24-7pm-4
pull_requests: [{"author":{"id":"U_kgDOB3EM8A","is_bot":false,"login":"notaryaman","name":""},"headRefName":"as-diningcommons","number":60,"title":"everything lol","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-4/pull/60"},{"author":{"id":"U_kgDOBdHhOA","is_bot":false,"login":"dhwang154","name":""},"headRefName":"dhwang154-ReqRequestTable","number":59,"title":"Dhwang154 req request table","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-4/pull/59"},{"author":{"id":"MDQ6VXNlcjQwNTQ2NDI3","is_bot":false,"login":"viditagrawal","name":""},"headRefName":"viditagrawal-controller-and-tests","number":56,"title":"Viditagrawal controller and tests","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-4/pull/56"}]
