
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-7pm-4
owner: ucsb-cs156-w24
repo_name: team02-w24-7pm-4
pull_requests: [{"author":{"id":"U_kgDOBXux7g","is_bot":false,"login":"wesleytruong","name":""},"headRefName":"wt-MenuItemReview-Controller","number":48,"title":"Wt - added menu item review controller","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-4/pull/48"},{"author":{"id":"U_kgDOBXux7g","is_bot":false,"login":"wesleytruong","name":""},"headRefName":"wt-MenuItemReview","number":47,"title":"created db table for MenuItemReview","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-4/pull/47"},{"author":{"id":"U_kgDOBXzOLw","is_bot":false,"login":"wesley-hung","name":""},"headRefName":"whung-Articles-40","number":46,"title":"implemeted GET by id for Articles","url":"https://github.com/ucsb-cs156-w24/team02-w24-7pm-4/pull/46"}]
